config/routes.rb
Rails.application.routes.draw do

  resources :item_masters
  root to: 'item_masters#index'

end

app/models/item_color.rb
class ItemColor < ActiveRecord::Base
  belongs_to :item_master
  has_many :item_details ,dependent: :destroy
  accepts_nested_attributes_for :item_details,  allow_destroy: true
end

app/models/item_detail.rb
class ItemDetail < ActiveRecord::Base
  belongs_to :item_color
end

app/models/item_master.rb
class ItemMaster < ActiveRecord::Base
  has_many :item_colors , dependent: :destroy
  accepts_nested_attributes_for :item_colors , allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_masters_controller.rb
class ItemMastersController < ApplicationController
   def index
    @item_master = ItemMaster.all
  end

  def show
    @item_master = ItemMaster.find(params[:id])
  end

  def new
    @item_master = ItemMaster.new
  end

  def create
    @item_master = ItemMaster.new(item_master_params)
    if @item_master.save
      redirect_to @item_master, notice: "Successfully created ItemMaster."
    else
      render :new
    end
  end

  def edit
    @item_master = ItemMaster.find(params[:id])
  end

  def update
    @item_master = ItemMaster.find(params[:id])
    if @item_master.update(item_master_params)
      redirect_to @item_master, notice: "Successfully updated ItemMaster."
    else
      render :edit
    end
  end

  def destroy
    @item_master = ItemMaster.find(params[:id])
    @item_master.destroy
    redirect_to item_masters_path, notice: "Successfully destroyed ItemMaster."
  end

  private

  def item_master_params
    # params.require(:item_master).permit(:title, :item_color=>[:name], :item_detail=>[:size_name])
    #params.require(:item_master).permit(:title, item_colors_attributes: [:name,  item_details_attributes: [:size_name]])
    params.require(:item_master).permit(:title, item_colors_attributes: [:id, :name, :_destroy,  item_details_attributes: [:id, :size_name, :_destroy]])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
  def notice_message
   alert_types = { notice: :success, alert: :danger }

   close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
   close_button = content_tag(:button, "×", close_button_options)

   alerts = flash.map do |type, message|
     alert_content = close_button + message

     alert_type = alert_types[type.to_sym] || type
     alert_class = "alert alert-#{alert_type} alert-dismissable"

     content_tag(:div, alert_content, class: alert_class)
   end

   alerts.join("\n").html_safe
 end
end

app/helpers/item_masters_helper.rb
module ItemMastersHelper
end

app/views/item_masters/_form.html.erb
<%= javascript_include_tag "application" %>
<%= form_for @item_master do |f| %>
  <% if @item_master.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@item_master.errors.count, "error") %> prohibited this item_master from being saved:</h2>
      <ul>
      <% @item_master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <%= f.fields_for :item_colors do |builder| %>
     <%= render 'item_color_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Color", f, :item_colors %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_masters/_item_color_fields.html.erb
<fieldset>
  <%= f.label :color, "Color" %><br />
  <%= f.text_area :name %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Color" %>
  <%= f.fields_for :item_details do |builder| %>
    <%= render 'item_detail_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Size", f, :item_details %>
</fieldset>

app/views/item_masters/_item_detail_fields.html.erb
<fieldset>
  <%= f.label :size_name, "Size" %>
  <%= f.text_field :size_name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/item_masters/edit.html.erb
<h1>Editing Item</h1>

<%= render "form" %>

app/views/item_masters/index.html.erb
<h1>Items</h1>

<% @item_master.each do |item_master| %>
  <div class="article">
    <h2><%= link_to item_master.title, item_master %></h2>
    <%#= pluralize(item_master.item_color.size, "Item_color") %>
  </div>
<% end %>

<p><%= link_to 'New Item', new_item_master_path %></p>

app/views/item_masters/new.html.erb
<h1>New Item</h1>

<%= render "form" %>

app/views/item_masters/show.html.erb
<h1><%= @item_master.title %></h1>

<ol class="item_colors">
<% @item_master.item_colors.each do |item_color| %>
  <li>
    <%= item_color.name %>
    <ol class="item_details">
      <% item_color.item_details.each do |item_detail| %>
        <li><%= item_detail.size_name %></li>
      <% end %>
    </ol>
  </li>
<% end %>
</ol>

<%= link_to 'Edit', edit_item_master_path(@item_master) %> |
<%= link_to 'Back to Items', item_masters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestUpPic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice_message %>
<%= yield %>

</body>
</html>